# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

pip install numpy

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [93]:
import numpy as np

#### 2. Print the numpy version

In [94]:
print("Numpy Version: ", np.__version__)

Numpy Version:  2.2.2


#### 3. Create a null array of size 5

In [95]:
arr = np.array([], ndmin=5)
print(arr)

[]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [96]:
arr = np.array([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0])
print(arr)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [97]:
arr = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [98]:
arr = np.array([1,2,4,0,4,0])
x = np.where(arr != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [99]:
from numpy import random

In [100]:
x = random.rand(4,4)
print(x)

[[0.76774803 0.15746113 0.63377893 0.27688505]
 [0.20973043 0.58208887 0.82364034 0.26270235]
 [0.45395402 0.2213452  0.74549733 0.9417168 ]
 [0.79297482 0.93896116 0.74917502 0.43032697]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [101]:
x = random.randint(1, 200, size=(15, 15))
print("Random 15x15 Array: \n", x)

Random 15x15 Array: 
 [[ 13  31 125 183  95 190 160  55 185  24  83 183 187 100  50]
 [190 137 190 132  40   8   5 160 193  32  30  12 171  84 108]
 [ 49  15   3  31 125  37  95  82   2 145  19  39 119 101  72]
 [ 73  20 107  74 183  48  99   7 184 129 196  84 132 168 129]
 [186 114 165  96   1  31  19  63 163 136 145  82 193 186  91]
 [179 118  27 161  99  54  72 172  70  62 163 143 103  23  26]
 [ 69  56   6 178  69  12 107 156 185 128  21 140  57   4 183]
 [112  79 102 198  13  47 179  15 104  20  90 163 137 126 177]
 [150 120  74 181  96 111  69 135   6 195  98 103  77 133 100]
 [ 31  28  36  69 169 169 128  73  36 121 185 195  70  17 150]
 [  6  54 148  30 161 118 195 179 138  72 193 168 188  53 169]
 [ 90  51 108 154 167 173  57 156  16 132 122 109  13  18 152]
 [ 44  69  67  29  67  52 137 101  83 110 190 141 159  37 148]
 [147 180 141 182  10  20  75 178 190 181  70  52  78 171 160]
 [ 28 108  28  56 177 186 186 110 147  83 180 134  59  86  60]]


In [102]:
min = np.min(x)
max = np.max(x)

print("Minimum value of Array: ", min, '\n')
print("Maximum value of Array: ", max, '\n')

Minimum value of Array:  1 

Maximum value of Array:  198 



#### 9. Create a random array of size 25 and find the mean value

In [103]:
x = random.randint(100, size=(25))
y = np.mean(x)

print("Random Array: \n", x, '\n')
print("Mean Value: ", y, '\n')

Random Array: 
 [91 51 19 91 12 81 66 44 87 95 92 52 68 57  5 21 63 77 43 93 66 98 71 33
 10] 

Mean Value:  59.44 



#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [104]:
array1 = ([2, 4, 9])
array2 = ([1, 14, 6])

print(array1)
print(array2)

[2, 4, 9]
[1, 14, 6]


10.1 What is the result of *a + b*?

In [105]:
[3, 18, 15]

[3, 18, 15]

10.2 What is the result of *a - b*?

In [106]:
[1, -10, 3]

[1, -10, 3]

10.3 What is the result of *a × b*?

In [107]:
[2, 56, 54]

[2, 56, 54]

10.4 What is the result of *a ÷ b*?

In [108]:
[2, 0, 2]

[2, 0, 2]

## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [109]:
arr = np.array([[10, 20, 30], [40,50,60], [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [110]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [111]:
arrRow = arr[1]

print("2nd Row of Array: \n", arrRow)

2nd Row of Array: 
 [40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [112]:
arrCol = arr[0:, 2]
print("3rd Column of Array: \n", arrCol)

3rd Column of Array: 
 [30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [113]:
print("Submatrix within Array:")
print(arr[1, 1:])
print(arr[2, 1:])

Submatrix within Array:
[50 60]
[80 90]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [114]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [115]:
print(arr[1, 1:3])
print(arr[2, 1:3])

[6 7]
[10 11]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [116]:
print(arr[0, 0:3:2])

[1 3]


4. Write code to reverse the order of rows in the matrix

In [117]:
print("Reversing the row order of the Matrix:")
print(arr[::-1]) 

Reversing the row order of the Matrix:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [118]:
print("Last two rows of the Matrix:")
print(arr[0:3, 2:4])

Last two rows of the Matrix:
[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [119]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [120]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [121]:
arr4 = np.stack((arr1, arr2), axis=0)
print(arr4)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [122]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [123]:
arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [124]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [125]:
from numpy import random

arr1 = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
arr2 = random.randint(1, 50, size=(4, 4))
arr3 = np.full((2, 3, 4), 1, dtype=int)

print("Array 1: \n", arr1, '\n')
print("Array 2: \n", arr2, '\n')
print("Array 3: \n", arr3, '\n')

Array 1: 
 [10 12 14 16 18 20 22 24 26 28] 

Array 2: 
 [[42 18 41 38]
 [ 6  7 20  7]
 [48 38 17 15]
 [10 37  6 20]] 

Array 3: 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [126]:
print("Array 2:\n", arr2, '\n')

# Sub task 1
newarr1 = arr1.reshape(2, 5)

print("New Array 1:\n", newarr1, '\n')

# Sub task 2
newarr2 = np.array([arr2[2], arr2[3] ])
print("Last 2 rows of Array 2:\n", newarr2, '\n')         
         
# Sub task 3
for x in arr2 : 
    arr2[arr2 % 2 == 0] = -1 # If the value is even (no remainder),
                             # then it will be replaced with -1
    
print("All even values replaced with -1 in Array 2: \n", arr2)

Array 2:
 [[42 18 41 38]
 [ 6  7 20  7]
 [48 38 17 15]
 [10 37  6 20]] 

New Array 1:
 [[10 12 14 16 18]
 [20 22 24 26 28]] 

Last 2 rows of Array 2:
 [[48 38 17 15]
 [10 37  6 20]] 

All even values replaced with -1 in Array 2: 
 [[-1 -1 41 -1]
 [-1  7 -1  7]
 [-1 -1 17 15]
 [-1 37 -1 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [127]:
arr2 = random.randint(1, 50, size=(4, 4))
print("Array 2:\n", arr2, '\n')

# Sub Task 1
arrMean = np.mean(arr2)
arrMedian = np.median(arr2)
arrStD = np.std(arr2)

print("Mean of Array 2: ", arrMean)
print("Median of Array 2: ", arrMedian)
print("Standard Deviation of Array 2: ", arrStD)

print('\n')

# Sub Task 2
for i, x in enumerate(arr2) : 
    sum = 0
    for y in x :
        sum = y + sum
    print("Sum of row", i + 1, ": ", sum)

# Sub Task 3


Array 2:
 [[12  8  4  4]
 [25  4 36 10]
 [ 6  1 25 43]
 [33 47 11 10]] 

Mean of Array 2:  17.4375
Median of Array 2:  10.5
Standard Deviation of Array 2:  14.66700697995334


Sum of row 1 :  28
Sum of row 2 :  75
Sum of row 3 :  75
Sum of row 4 :  101


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.