# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

pip install numpy

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [1]:
import numpy as np

#### 2. Print the numpy version

In [2]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [116]:
arr = np.array([], ndmin=5)
print(arr)

[]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [117]:
arr = np.array([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0])
print(arr)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [115]:
arr = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [118]:
arr = np.array([1,2,4,0,4,0])
x = np.where(arr != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [88]:
from numpy import random

In [119]:
x = random.rand(4,4)
print(x)

[[0.70128106 0.76829045 0.25201817 0.73728724]
 [0.50601378 0.21410517 0.15707883 0.0358365 ]
 [0.58310207 0.60470945 0.81007728 0.39448006]
 [0.99796211 0.05976257 0.35853804 0.88134793]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [123]:
x = random.randint(100, size=(15, 15))
print(x)

[[13 53 26 82 64 83 46 29 67 22 45 28 81 37 48]
 [90 53 66 40  2 76 98 71 26 27 10 41 87 87 86]
 [93 41 49 92 88 18  3 99 46  4 69 66 73 20 57]
 [77 46 57 78 56 67 65 42 14 38 31 76 21 35 36]
 [17  1 98 51 41 43 56 50 22 75 68 45 86 15 23]
 [53 11 33 51 30 97  5 35 86 99 51 86 78 71 32]
 [90 56 72 76 90 95 30 12 53 73 34 98 75 97 60]
 [12 53 92 96  4 37 83 28 56 34 62 50 16 39 86]
 [45 67 28 93  6 59 35 94 20 57 11 99 95 10 79]
 [ 4 38 85 80 97  9 43 94 65 94 47 72 37 17 25]
 [48 85 81 40  3 49 32 27  8 75 42 20 53 61  1]
 [ 6 21 75 88 54 99 22 64 44 48 45  0 99 64 31]
 [26  3 83 13 43 33 98 36 75 36 61 73 68 65 42]
 [13 48 59 47 51 46 85 21 26  1 27 11 57 66 74]
 [55 52  1 91 85 87 46 48 60 64 19 58 47  9 59]]


In [124]:
min = np.min(x)
max = np.max(x)

print(min)
print(max)

0
99


#### 9. Create a random array of size 25 and find the mean value

In [125]:
x = random.randint(100, size=(25))
y = np.mean(x)

print(x)
print(y)

[54 50 30 55 87 10  9 12 85 93 65 76 27 32 87 83 95 63 12 30 10  7 48 10
 71]
48.04


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [126]:
array1 = ([2, 4, 9])
array2 = ([1, 14, 6])

print(array1)
print(array2)

[2, 4, 9]
[1, 14, 6]


10.1 What is the result of *a + b*?

In [94]:
[3, 18, 15]

[3, 18, 15]

10.2 What is the result of *a - b*?

In [95]:
[1, -10, 3]

[1, -10, 3]

10.3 What is the result of *a × b*?

In [96]:
[2, 56, 54]

[2, 56, 54]

10.4 What is the result of *a ÷ b*?

In [97]:
[2, 0, 2]

[2, 0, 2]

## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [127]:
arr = np.array([[10, 20, 30], [40,50,60], [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [99]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [100]:
print(arr[2, 0:])

[70 80 90]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [101]:
arr1 = np.array(np.where(arr == 3))
print(arr1)

[]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [102]:
print(arr[1, 1:])
print(arr[2, 1:])

[50 60]
[80 90]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [141]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [104]:
print(arr[1, 1:3])
print(arr[2, 1:3])

[6 7]
[10 11]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [105]:
print(arr[0, 0:3:2])

[1 3]


4. Write code to reverse the order of rows in the matrix

In [144]:
print(arr[::-1, ::-1]) 

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [146]:
print(arr[0:3, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [108]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [109]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [110]:
arr4 = np.stack((arr1, arr2), axis=1)
print(arr4)

[[11 44]
 [ 7  5]
 [33 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [150]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [112]:
arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [151]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [46]:
from numpy import random

arr1 = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
arr2 = random.randint(1, 50, size=(4, 4))
arr3 = np.full((2, 3, 4), 1, dtype=int)

print("Array 1: \n", arr1, '\n')
print("Array 2: \n", arr2, '\n')
print("Array 3: \n", arr3, '\n')

Array 1: 
 [10 12 14 16 18 20 22 24 26 28] 

Array 2: 
 [[35 48 11 22]
 [ 4 40 42  2]
 [46 25  5  6]
 [25 36 14 49]] 

Array 3: 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [65]:
print("Array 2:\n", arr2, '\n')

# Sub task 1
newarr1 = arr1.reshape(2, 5)

print("New Array 1:\n", newarr1, '\n')

# Sub task 2
newarr2 = np.array([arr2[2], arr2[3] ])
print("Last 2 rows of Array 2:\n", newarr2, '\n')         
         
# Sub task 3
for x in arr2 : 
    arr2[arr2 % 2 == 0] = -1 # If the value is even (no remainder),
                             # then it will be replaced with -1
    
print("All even values replaced with -1 in Array 2: \n", arr2)

Array 2:
 [[40 38  8 12]
 [38 30 23 27]
 [48  5 20  7]
 [ 4 33 18 47]] 

New Array 1:
 [[10 12 14 16 18]
 [20 22 24 26 28]] 

Last 2 rows of Array 2:
 [[48  5 20  7]
 [ 4 33 18 47]] 

All even values replaced with -1 in Array 2: 
 [[-1 -1 -1 -1]
 [-1 -1 23 27]
 [-1  5 -1  7]
 [-1 33 -1 47]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [71]:
arr2 = random.randint(1, 50, size=(4, 4))
print("Array 2:\n", arr2, '\n')

# Sub Task 1
arrMean = np.mean(arr2)
arrMedian = np.median(arr2)
arrStD = np.std(arr2)

print("Mean of Array 2: ", arrMean)
print("Median of Array 2: ", arrMedian)
print("Standard Deviation of Array 2: ", arrStD)

print('\n')

# Sub Task 2
for i, x in enumerate(arr2) : 
    sum = 0
    for y in x :
        sum = y + sum
    print("Sum of row", i + 1, ": ", sum)

# Sub Task 3


Array 2:
 [[16 47 19 38]
 [ 7 22  9 30]
 [30 17  4  7]
 [24 45 34  5]] 

Mean of Array 2:  22.125
Median of Array 2:  20.5
Standard Deviation of Array 2:  13.665078667903819


Sum of row 1 :  120
Sum of row 2 :  68
Sum of row 3 :  58
Sum of row 4 :  108


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.