# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

pip install numpy

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [6]:
import numpy as np

#### 2. Print the numpy version

In [7]:
print("Numpy Version: ", np.__version__)

Numpy Version:  2.0.2


#### 3. Create a null array of size 5

In [8]:
arr = np.array([], ndmin=5)
print(arr)

[]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [9]:
arr = np.array([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0])
print(arr)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [10]:
arr = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [11]:
arr = np.array([1,2,4,0,4,0])
x = np.where(arr != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [12]:
from numpy import random

In [14]:
x = random.rand(4,4)
print(x)

[[0.69115326 0.6936752  0.26278502 0.60644327]
 [0.49825899 0.05197858 0.7946404  0.40490537]
 [0.4871787  0.34257541 0.93205628 0.56448855]
 [0.73957804 0.7874088  0.37728177 0.82881298]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [15]:
x = random.randint(1, 200, size=(15, 15))
print("Random 15x15 Array: \n", x)

Random 15x15 Array: 
 [[ 38 142 114  84 119 155  79  88 170 150  17 181 105 125  49]
 [137  32  72 154 170  35 109   6 199 121  59 142 127  53 158]
 [  9  15  52 185  21 120 109  85 119  41 139 126 129 137  77]
 [ 10 164  17  44 156 106  70 101 123 190 140  55  40  87 146]
 [109  81  23 126 174  15  95  20  43  91  14 135 150 163  48]
 [143  75 167 144 134 194  75  32  71  23  16 125 164 100 195]
 [199 128 153  22 139 141 107  13   7 177  73  54  72 152  35]
 [139  50 116  54  43  76 125  58   6  65 113 164  14 158 144]
 [ 83 100 168  76  20  40 124   1  36  53  39 134 187  12 186]
 [177 138 158  24  16  88 164   7 170  28   1  55  59 175  52]
 [ 31  47  93  68  97  14  15  20 117 111 139 179  88  37 184]
 [117 191 183 161  10   4 110 186  51 123 154 187  73  87  99]
 [ 51  50 102  15 190 182 171 195  14  94 178 125 128  77 198]
 [154 126  83 151 197  96  70 117  72 199  17  30  25 141  76]
 [158 107  11  86  17  13  91 171  68 104 104 128 149 117 123]]


In [16]:
min = np.min(x)
max = np.max(x)

print("Minimum value of Array: ", min, '\n')
print("Maximum value of Array: ", max, '\n')

Minimum value of Array:  1 

Maximum value of Array:  199 



#### 9. Create a random array of size 25 and find the mean value

In [17]:
x = random.randint(100, size=(25))
y = np.mean(x)

print("Random Array: \n", x, '\n')
print("Mean Value: ", y, '\n')

Random Array: 
 [33 88 41 82 91 27 84 27  1 65  9 42 39 69 74 87 12 39 55 65 97 48 53 71
 13] 

Mean Value:  52.48 



#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [23]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print(array1)
print(array2)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [24]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [25]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [27]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [28]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [29]:
arr = np.array([[10, 20, 30], [40,50,60], [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [30]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [31]:
arrRow = arr[1]

print("2nd Row of Array: \n", arrRow)

2nd Row of Array: 
 [40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [32]:
arrCol = arr[0:, 2]
print("3rd Column of Array: \n", arrCol)

3rd Column of Array: 
 [30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [33]:
print("Submatrix within Array:")
print(arr[1, 1:])
print(arr[2, 1:])

Submatrix within Array:
[50 60]
[80 90]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [34]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [35]:
print(arr[1, 1:3])
print(arr[2, 1:3])

[6 7]
[10 11]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [36]:
print(arr[0, 0:3:2])

[1 3]


4. Write code to reverse the order of rows in the matrix

In [37]:
print("Reversing the row order of the Matrix:")
print(arr[::-1]) 

Reversing the row order of the Matrix:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [38]:
print("Last two rows of the Matrix:")
print(arr[0:3, 2:4])

Last two rows of the Matrix:
[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [39]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [40]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [41]:
arr4 = np.stack((arr1, arr2), axis=0)
print(arr4)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [42]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [43]:
arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [44]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [45]:
from numpy import random

arr1 = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
arr2 = random.randint(1, 50, size=(4, 4))
arr3 = np.full((2, 3, 4), 1, dtype=int)

print("Array 1: \n", arr1, '\n')
print("Array 2: \n", arr2, '\n')
print("Array 3: \n", arr3, '\n')

Array 1: 
 [10 12 14 16 18 20 22 24 26 28] 

Array 2: 
 [[17 31 27 17]
 [12 47 40 38]
 [12 47 15 42]
 [48 36  6  2]] 

Array 3: 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [46]:
print("Array 2:\n", arr2, '\n')

# Sub task 1
newarr1 = arr1.reshape(2, 5)

print("New Array 1:\n", newarr1, '\n')

# Sub task 2
newarr2 = np.array([arr2[2], arr2[3] ])
print("Last 2 rows of Array 2:\n", newarr2, '\n')         
         
# Sub task 3
for x in arr2 : 
    arr2[arr2 % 2 == 0] = -1 # If the value is even (no remainder),
                             # then it will be replaced with -1
    
print("All even values replaced with -1 in Array 2: \n", arr2)

Array 2:
 [[17 31 27 17]
 [12 47 40 38]
 [12 47 15 42]
 [48 36  6  2]] 

New Array 1:
 [[10 12 14 16 18]
 [20 22 24 26 28]] 

Last 2 rows of Array 2:
 [[12 47 15 42]
 [48 36  6  2]] 

All even values replaced with -1 in Array 2: 
 [[17 31 27 17]
 [-1 47 -1 -1]
 [-1 47 15 -1]
 [-1 -1 -1 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [51]:
arr2 = random.randint(1, 50, size=(4, 4))
print("Array 2:\n", arr2, '\n')

# Sub Task 1
arrMean = np.mean(arr2)
arrMedian = np.median(arr2)
arrStD = np.std(arr2)

print("Mean of Array 2: ", arrMean)
print("Median of Array 2: ", arrMedian)
print("Standard Deviation of Array 2: ", arrStD)

print('\n')

# Sub Task 2
for i, x in enumerate(arr2) : 
    sum = 0
    for y in x :
        sum = y + sum
    print("Sum of row", i + 1, ": ", sum)

# Sub Task 3
max = np.max(arr2)

print("\nMaximum value of Array 2: ", max)
print("The index of the maximum value is: ", np.where(arr2 == max))

Array 2:
 [[ 4 36 47 28]
 [40  1 44  4]
 [34 40 44 18]
 [25 46  9 47]] 

Mean of Array 2:  29.1875
Median of Array 2:  35.0
Standard Deviation of Array 2:  16.34479561664813


Sum of row 1 :  115
Sum of row 2 :  89
Sum of row 3 :  136
Sum of row 4 :  127

Maximum value of Array 2:  47
The index of the maximum value is:  (array([0, 3]), array([2, 3]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [49]:
#Create a (10,10) array containing random floating-point numbers between 0 and 1
arr = np.random.rand(10, 10)
print(arr)

print('\n')

#Find the minimum and maximum value along each column
minvalue= np.min(arr, axis=0)
print("Minimum value along each column: ", minvalue)


print('\n')

#Find the indices of the top 5 largest values in the entire array
maxvalue=np.max(arr)
#convert it to 10x10 by 1D to sort the array
flattenarr=arr.flatten()
#sort the array
sort=np.argsort(flattenarr)
#find the top 5 values
top5=sort[-5:]
top5values=flattenarr[top5]
top5sort=np.sort(top5values)[::-1]
print("Top 5 Maximum value of the entire array: ", top5sort)

[[0.13848691 0.77252801 0.85059351 0.15946946 0.66771005 0.52521836
  0.58708268 0.51406143 0.06722249 0.8636541 ]
 [0.14310555 0.79823088 0.64564918 0.13955607 0.15142305 0.63883398
  0.29866802 0.86497262 0.39582823 0.09818745]
 [0.63775118 0.76329811 0.12912596 0.51033575 0.76307064 0.64640624
  0.43752421 0.33390922 0.34646728 0.31475443]
 [0.41021417 0.35524031 0.90435607 0.55258328 0.17202358 0.95143318
  0.88386348 0.21485863 0.65277969 0.28921827]
 [0.6392908  0.85119075 0.1750707  0.14439441 0.93836552 0.79344269
  0.26246153 0.88343748 0.34318837 0.47679775]
 [0.82079721 0.36401753 0.58605365 0.31361704 0.19176748 0.99082389
  0.73993282 0.51820771 0.23813225 0.3999404 ]
 [0.75281017 0.16768242 0.82977022 0.58459514 0.8143592  0.33252786
  0.57671687 0.92837918 0.39096984 0.67126219]
 [0.87329063 0.72854746 0.45750434 0.99595055 0.67455231 0.42297182
  0.07517514 0.82178725 0.72070071 0.13073778]
 [0.41289078 0.27876169 0.1366187  0.30313795 0.1888649  0.68544967
  0.37931163